name: Deploy de Página web
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Github pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build com Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload do Artefato
        uses: actions/upload-pages-artifact@v3

  deploy:
    permissions:
      pages: write
      id-token: write
      contents: read
    environment: 
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4